output: 'lib/src/generated_bindings.dart'
name: 'FreetypeBinding'
description: 'Freetype binding for dart'

llvm-path:
  - 'C:\Program Files\LLVM'

headers:
  entry-points:   
    - 'freetype/include/ft2build.h'         
    - 'freetype/include/freetype/freetype.h' 
    - 'freetype/include/freetype/ftglyph.h' 
    - 'freetype/include/freetype/ftsystem.h'  
    - 'freetype/include/freetype/ftimage.h' 
    - 'freetype/include/freetype/fterrors.h' 
    - 'freetype/include/freetype/ftoutln.h'
    - 'freetype/include/freetype/tttables.h'
    - 'freetype/include/freetype/ttnameid.h'
    - 'freetype/include/freetype/fttypes.h'
    - 'freetype/include/freetype/ftmodapi.h'
    - 'freetype/include/freetype/fttrigon.h'
    - 'freetype/include/freetype/ftsizes.h'
    - 'freetype/include/freetype/ftstroke.h'
    - 'freetype/include/freetype/ftadvanc.h'
    - 'freetype/include/freetype/ftlcdfil.h'
    - 'freetype/include/freetype/ftcache.h'
    - 'freetype/include/freetype/ftbitmap.h'
    - 'freetype/include/freetype/ftmm.h'
    - 'freetype/include/freetype/ftbbox.h'
    - 'freetype/include/freetype/ftsnames.h'
    - 'freetype/include/freetype/ftwinfnt.h'
    - 'freetype/include/freetype/ftsynth.h'
    - 'freetype/include/freetype/ftxf86.h'
    - 'freetype/include/freetype/t1tables.h'
    - 'freetype/include/freetype/ftotval.h'
    - 'freetype/include/freetype/ftcid.h'
    - 'freetype/include/freetype/ftgasp.h'
    - 'freetype/include/freetype/ftparams.h'
    - 'freetype/include/freetype/ftdriver.h'

  include-directives:
    - 'freetype/include/**'
    - 'freetype/include/freetype/**'

compiler-opts:
  - '-Ifreetype/include/'