name: freetype_dart
version: 1.0.2
description: freetype dart bindings
homepage: https://github.com/klsruan/freetype_dart
repository: https://github.com/klsruan/freetype_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.1  
  ffi: ^2.1.4
  image: ^4.5.4

dev_dependencies:
  ffigen: ^19.1.0

ffigen:
  output: 'lib/src/generated_bindings.dart'
  name: 'FreetypeBinding'
  description: 'Freetype binding for dart'

  llvm-path:
    - 'C:\Program Files\LLVM'

  headers:
    entry-points:   
      - 'freetype/include/ft2build.h'         
      - 'freetype/include/freetype/freetype.h' 
    include-directives:
      - 'freetype/include/**'
      - 'freetype/include/freetype/**'
      - 'freetype/include/ft2build.h'
      - 'freetype/include/freetype/fterrdef.h'  
      - 'freetype/include/freetype/fterrors.h' 
      - 'freetype/include/freetype/ftimage.h' 
      - 'freetype/include/freetype/fttypes.h'  
      - 'freetype/include/freetype/ftglyph.h'
      - 'freetype/include/freetype/tttables.h'

  compiler-opts:
    - '-Ifreetype/include/'